resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github.com_jlesneski
      name: jlesneski/terraform-templates

trigger:
- main

variables:
  ARTIFACT_NAME: 'terraformArtifact'

stages:
##### Run Build #####
- template: src/stages/build/build_terraform_v1.yml@templates
  parameters:
    terraformArtifactName: ${{ variables.ARTIFACT_NAME }}
##### Run Deploy #####
- template: src/stages/deploy/deploy_terraform_v1.yml@templates
  parameters:
    terraformArtifactName: ${{ variables.ARTIFACT_NAME }}

- stage: QA_PLAN
  dependsOn: DEV_Apply
  jobs:
    - job: QA_PLAN
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName:  ${{ variables.ARTIFACT_NAME }}
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: TerraformInstaller@0
        displayName: 'Install Terraform latest'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceAWS: 'lucidiaitAWS'
          backendAWSBucketName: 'lucidiaterraform'
          backendAWSKey: 'terraform/terraform.tfstate'
      - task: TerraformTaskV3@3
        displayName: 'TerraformWorkspace QA'
        inputs:
          provider: aws
          command: custom
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          customCommand: workspace
          commandOptions: 'select QA'
          environmentServiceNameAWS: lucidiaitAWS
          backendServiceAWS: lucidiaitAWS
          backendAWSBucketName: lucidiaterraform
          backendAWSKey: terraform/terraform.tfstate
      - task: TerraformTaskV3@3
        displayName: 'Terraform plan: aws'
        inputs:
          provider: aws
          command: plan
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAWS: lucidiaitAWS
- stage: Deploy_QA_APPLY
  dependsOn: QA_PLAN
  jobs:
    - deployment: 'QA'
      environment: 'QA'
    - job: Deploy_QA_APPLY
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: DownloadBuildArtifacts@1
        inputs:
          buildType: 'current'
          downloadType: 'single'
          artifactName:  ${{ variables.ARTIFACT_NAME }}
          downloadPath: '$(System.ArtifactsDirectory)'
      - task: TerraformInstaller@0
        displayName: 'Install Terraform latest'
      - task: TerraformTaskV3@3
        inputs:
          provider: 'aws'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          backendServiceAWS: 'lucidiaitAWS'
          backendAWSBucketName: 'lucidiaterraform'
          backendAWSKey: 'terraform/terraform.tfstate'
      - task: TerraformTaskV3@3
        displayName: 'TerraformWorkspace QA'
        inputs:
          provider: aws
          command: custom
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          customCommand: workspace
          commandOptions: 'select QA'
          environmentServiceNameAWS: lucidiaitAWS
          backendServiceAWS: lucidiaitAWS
          backendAWSBucketName: lucidiaterraform
          backendAWSKey: terraform/terraform.tfstate
      - task: TerraformTaskV3@3
        displayName: 'Terraform plan: aws'
        inputs:
          provider: aws
          command: plan
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAWS: lucidiaitAWS
      - task: TerraformTaskV3@3
        displayName: 'Terraform apply: aws'
        inputs:
          provider: aws
          command: apply
          workingDirectory: '$(System.DefaultWorkingDirectory)'
          environmentServiceNameAWS: lucidiaitAWS
