# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'terraform'
        publishLocation: 'pipeline'
- stage: DeployDev_PLAN
  jobs:
    - job: DeployDev_PLAN
      pool:
        vmImage: ubuntu-latest
      steps:
      - download: aws
        artifact: terraform  
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
        displayName: 'Install Terraform latest'
      - script: |
          pwd
          ls -laR
        displayName: 'Command Line Script'
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: 'Terraform init: aws'
        inputs:
          provider: aws
          workingDirectory: '$(System.DefaultWorkingDirectory)/_jlesneski.terraform-workshop/terraform/s'
          backendServiceAWS: lucidiaitAWS
          backendAWSBucketName: lucidiaterraform
          backendAWSKey: terraform/terraform.tfstate
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: 'TerraformWorkspace DEV'
        inputs:
          provider: aws
          command: custom
          workingDirectory: '$(System.DefaultWorkingDirectory)/_jlesneski.terraform-workshop/terraform/s'
          customCommand: workspace
          commandOptions: 'select DEV'
          environmentServiceNameAWS: lucidiaitAWS
          backendServiceAWS: lucidiaitAWS
          backendAWSBucketName: lucidiaterraform
          backendAWSKey: terraform/terraform.tfstate
      - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
        displayName: 'Terraform plan: aws'
        inputs:
          provider: aws
          command: plan
          workingDirectory: '$(System.DefaultWorkingDirectory)/_jlesneski.terraform-workshop/terraform/s'
          environmentServiceNameAWS: lucidiaitAWS
