resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github.com_jlesneski
      name: jlesneski/terraform-templates

trigger:
- main

variables:
  ARTIFACT_NAME: 'terraformArtifact'

stages:
##### Run Build #####
- template: src/stages/build/build_terraform_v1.yml@templates
  parameters:
    terraformArtifactName: ${{ variables.ARTIFACT_NAME }}
##### Run Deploy #####
- template: src/stages/deploy/deploy_terraform_v1.yml@templates
  parameters:
    terraformArtifactName: ${{ variables.ARTIFACT_NAME }}