trigger:
- none

resources:
  pipelines:
  - pipeline: aws  # Name of the pipeline resource
    source: jlesneski.terraform-workshop # Name of the triggering pipeline
    trigger: 
      branches:
      - main

variables:
  vmImageName: 'ubuntu-latest'

jobs:
- deployment: Deploy
  displayName: DEV 
  environment: dev
  pool: 
    vmImage: $(vmImageName)
  strategy:
    runOnce:
      deploy:
        steps:          
        - download: aws
          artifact: terraform  
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform latest'
        - script: |
            pwd
            ls -laR
          displayName: 'Command Line Script'
